/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TodoListImport } from './routes/todo-list'
import { Route as DummyImport } from './routes/dummy'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TodoListRoute = TodoListImport.update({
  id: '/todo-list',
  path: '/todo-list',
  getParentRoute: () => rootRoute,
} as any)

const DummyRoute = DummyImport.update({
  id: '/dummy',
  path: '/dummy',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dummy': {
      id: '/dummy'
      path: '/dummy'
      fullPath: '/dummy'
      preLoaderRoute: typeof DummyImport
      parentRoute: typeof rootRoute
    }
    '/todo-list': {
      id: '/todo-list'
      path: '/todo-list'
      fullPath: '/todo-list'
      preLoaderRoute: typeof TodoListImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dummy': typeof DummyRoute
  '/todo-list': typeof TodoListRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dummy': typeof DummyRoute
  '/todo-list': typeof TodoListRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dummy': typeof DummyRoute
  '/todo-list': typeof TodoListRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dummy' | '/todo-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dummy' | '/todo-list'
  id: '__root__' | '/' | '/dummy' | '/todo-list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DummyRoute: typeof DummyRoute
  TodoListRoute: typeof TodoListRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DummyRoute: DummyRoute,
  TodoListRoute: TodoListRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dummy",
        "/todo-list"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dummy": {
      "filePath": "dummy.tsx"
    },
    "/todo-list": {
      "filePath": "todo-list.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
